- name: List RAID information on a HPE system
  hosts: localhost
  gather_facts: false
  vars_files: my_var.yml

  tasks:
    - name: Test that my module works
      raid_info:
         host: "{{ host }}"
         username: "{{ username }}"
         password: "{{ password }}"
         raid: "{{ raid }}"
         dataguard: "{{ dataguard }}"
         logicaldrivename: "{{ logicaldrivename }}"
      register: result 
    - name: show output
      debug:
         var: result  
